
export const TOOGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const FILTER_CARDS = 'FILTER_CARDS';
export const ORDER_CARDS = 'ORDER_CARDS';
export const GET_RANDOM_CHARACTER = 'GET_RANDOM_CHARACTER';
export const GET_CHARACTER = 'GET_CHARACTER';
export const REMOVE_CHARACTER = 'REMOVE_CHARACTER';
export const GET_PAGINATE_CHARACTER = 'GET_PAGINATE_CHARACTER';